### ISSUE TITLE
NPM is not defined

### ISSUE THREAD

**Issue by AllanPinheiroDeLima** [udondan/googlefonts#3]
I have an annoying problem with this package. I put everything in ordem, just like it is described at Atmosphere. But I keep receiving the error 
Uncaught ReferenceError: Npm is not defined

All my other packages use npm.require and none of them have issues. 

Someone knows whats going on?

**Comment by udondan** [comment]
Hi Allen,

sorry about that. Unfortunately I'm no longer using Meteor since 2 years now.

If someone wants to look into this and send a PR, that would be very appreciated. I'd take care of releasing the update to Atmosphere.

Thanks,
Daniel

**Comment by AllanPinheiroDeLima** [comment]
No problem, thanks :)
